### ISSUE TITLE
Runtime: out of memory in Collect

### ISSUE THREAD

**Issue by laurentiuilie** [dsoprea/go-exif#45]
Something is happening with the memory in `Collect`. It might be a memory leak that I couldn't figure out my self.

Here is the error I'm getting with stacktrace:

```
fatal error: runtime: out of memory

runtime stack:
runtime.throw(0xe421fd, 0x16)
        /usr/local/go/src/runtime/panic.go:1116 +0x72
runtime.sysMap(0xc134000000, 0x4000000, 0x1649638)
        /usr/local/go/src/runtime/mem_bsd.go:73 +0xc5
runtime.(*mheap).sysAlloc(0x1634dc0, 0x400000, 0x7501a9040, 0x7501aa470)
        /usr/local/go/src/runtime/malloc.go:715 +0x1cd
runtime.(*mheap).grow(0x1634dc0, 0x1, 0x0)
        /usr/local/go/src/runtime/mheap.go:1286 +0x11c
runtime.(*mheap).allocSpan(0x1634dc0, 0x1, 0x74fd52000, 0x1649648, 0x7501aa360)
        /usr/local/go/src/runtime/mheap.go:1124 +0x65d
runtime.(*mheap).alloc.func1()
        /usr/local/go/src/runtime/mheap.go:871 +0x64
runtime.systemstack(0x7fffdd9eaf80)
        /usr/local/go/src/runtime/asm_amd64.s:370 +0x66
runtime.mstart()
        /usr/local/go/src/runtime/proc.go:1041

goroutine 315006 [running]:
runtime.systemstack_switch()
        /usr/local/go/src/runtime/asm_amd64.s:330 fp=0xc0001f2030 sp=0xc0001f2028 pc=0x4699c0
runtime.(*mheap).alloc(0x1634dc0, 0x1, 0x410120, 0x7501a6140)
        /usr/local/go/src/runtime/mheap.go:865 +0x81 fp=0xc0001f2080 sp=0xc0001f2030 pc=0x42b091
runtime.(*mcentral).grow(0x1645a18, 0x0)
        /usr/local/go/src/runtime/mcentral.go:255 +0x79 fp=0xc0001f20c0 sp=0xc0001f2080 pc=0x41d819
runtime.(*mcentral).cacheSpan(0x1645a18, 0x60)
        /usr/local/go/src/runtime/mcentral.go:106 +0x2bc fp=0xc0001f2108 sp=0xc0001f20c0 pc=0x41d34c
runtime.(*mcache).refill(0x701659560, 0x20)
        /usr/local/go/src/runtime/mcache.go:138 +0x85 fp=0xc0001f2128 sp=0xc0001f2108 pc=0x41ce35
runtime.(*mcache).nextFree(0x701659560, 0x20, 0x30, 0x30, 0xc133ffcc30)
        /usr/local/go/src/runtime/malloc.go:868 +0x87 fp=0xc0001f2160 sp=0xc0001f2128 pc=0x411a67
runtime.mallocgc(0xf0, 0xe140c0, 0xdf1c01, 0x16477e0)
        /usr/local/go/src/runtime/malloc.go:1036 +0x793 fp=0xc0001f2200 sp=0xc0001f2160 pc=0x4123a3
runtime.newobject(0xe140c0, 0x0)
        /usr/local/go/src/runtime/malloc.go:1165 +0x38 fp=0xc0001f2230 sp=0xc0001f2200 pc=0x412798
github.com/dsoprea/go-exif/v2.(*IfdEnumerate).Collect(0xc0001f2780, 0xc000000008, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0)
        /go/pkg/mod/github.com/dsoprea/go-exif/v2@v2.0.0-20200321225314-640175a69fe4/ifd_enumerate.go:958 +0x3ef fp=0xc0001f2718 sp=0xc0001f2230 pc=0xc4a6cf
github.com/dsoprea/go-exif/v2.Collect(0xc00064c030, 0xc0006f61a0, 0xc00053403c, 0x1ffc4, 0x3fdc4, 0x1016da0, 0x16477e0, 0x8, 0x0, 0x0, ...)
        /go/pkg/mod/github.com/dsoprea/go-exif/v2@v2.0.0-20200321225314-640175a69fe4/exif.go:211 +0x232 fp=0xc0001f27e8 sp=0xc0001f2718 pc=0xc41da2
```

Would be great if someone can have look and find out what is going on here.

**Comment by dsoprea** [comment]
This is reproducible? How are you calling into go-exif? Please share the image that you're operating on. 

Have you tried updating to v3? v2 support is going to be limited.

**Comment by dsoprea** [comment]
Please reopen when you can supply the requested information.

**Comment by laurentiuilie** [comment]
I don't have an image, that's why I couldn't reproduce this issue.
It might be an isolated case.

Here is how is called:
```
func GetIfdIndex(img io.Reader) (ifdIndex exif.IfdIndex, err error) {
	buf, err := ioutil.ReadAll(img)
	if err != nil && !errors.Is(err, io.EOF) {
		return ifdIndex, fmt.Errorf("error reading image: %w", err)
	}
	rawExif, err := exif.SearchAndExtractExif(buf)
	if err != nil {
		return ifdIndex, fmt.Errorf("error finding exif info: %w", err)
	}
	ifd := exif.NewIfdMappingWithStandard()
	tag := exif.NewTagIndex()
	_, ifdIndex, err = exif.Collect(ifd, tag, rawExif)
	if err != nil {
		return ifdIndex, fmt.Errorf("error collecting IFD info: %w", err)
	}
	return ifdIndex, nil
}
```

I'll consider upgrading to v3. Thanks for looking into this.

**Comment by dsoprea** [comment]
I'm asking how you're calling it. Are you integrating go-exif and calling a function in it? What is that function? Are you just calling a CLI command from go-exif or another project that's calling go-exif? Which command?

**Comment by laurentiuilie** [comment]
Not through CLI, using `go-exif` into a project where I'm trying to get exif information. 

In order to find a specific tag like `DateTime` I'm using `FindTagWithName` 
```
ifdTags, err := ifdIndex.RootIfd.FindTagWithName("DateTime")
```
which means I need `IfdIndex ` 
```
ifdIndex, err := GetIfdIndex(image)
```
and this is what you can check in my previous comment.

**Comment by dsoprea** [comment]
Sorry about that. Traveling.

Yes. Please try v3. That'd be the low-hanging fruit.

I'd also really recommend using the format-specific parsers. That brute-force search function can be a dangerous thing. It's going to return the EXIF block from its header to the end of the file because EXIF doesn't have a built-in method to determine it's own length. You'd run out of memory if you're parsing through a large image, and the EXIF blob is near the beginning of the file, if you have some kind of memory restriction. You'd also likely run out of memory if someone passed you a video file that happened to have an EXIF blob in it (which some *do* support) for the same reason. By being format-specific, you're extracting the EXIF information first before attempting to parse it.
